# Generated by Django 4.2.16 on 2024-10-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='name',
            new_name='airline_name',
        ),
    ]
