# Generated by Django 4.2.16 on 2024-10-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_rename_name_airline_airline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='airline_name',
            new_name='name',
        ),
    ]
